services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_container
    ports:
      - '5678:5678'
    volumes:
      - ~/.n8n:/home/node/.n8n
    environment:
      - N8N_EDITOR_URL=http://localhost:5678/
    restart: unless-stopped
